/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ramadhan Mohammed Mkoma (https://sketchfab.com/ramadhanmkoma9)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/angular-brand-480c6c17299f4b6c9a557f2728ad3906
Title: Angular Brand
*/

import React, { useRef } from 'react'
import { Float, useGLTF, useAnimations } from '@react-three/drei'

const AngularLogo = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/angular_brand.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <Float floatIntensity={2.5}>
      <group ref={group} {...props} dispose={null} name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 34]}>
          <group
            name="5ce00caaade5466b9b19b5411e5fb704fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="logo"
                  position={[0, 0, 151.109]}
                  rotation={[-Math.PI / 2, 0, 2.904]}
                  scale={190.107}>
                  <mesh
                    name="logo_Material001_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.logo_Material001_0.geometry}
                    material={materials['Material.001']}
                  > 
                    <meshStandardMaterial
                        color={'#ff1744'}       
                        metalness={0.4}
                        roughness={0.5}
                    />
                  </mesh>
                </group>
                <group
                  name="Camera"
                  position={[-40.863, 187.91, 805.81]}
                  rotation={[0, 1.508, -0.258]}
                  scale={100}>
                  <group name="Object_7" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </Float>
  )
}

useGLTF.preload('/models/angular_brand.glb')

export default AngularLogo
