/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/c-e3a5d3e564a64fb0ab39665f44632520
Title: C#
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const CsharpLogo = (props) => {
  const { nodes, materials } = useGLTF('/models/csharp.glb');
  
  return (
    <Float floatIntenity={0.7} >
      <group scale={0.01} {...props} dispose={null}>
        <mesh
          geometry={nodes['C#_C#_0'].geometry}
          material={materials.material}
          rotation={[-Math.PI / 2, 0, Math.PI / 3]}
          scale={4}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/models/csharp.glb')

export default CsharpLogo
