/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: stanleyatabiishabor (https://sketchfab.com/stanleyatabiishabor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/javascript-b220d3f7900f49b6a0d1f0ad15e2d1df
Title: javascript
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const JavascriptLogo = (props) => {
  const { nodes, materials } = useGLTF('/models/javascript.glb')
  return (
    <Float floatIntensity={1.5}>
        <group {...props} dispose={null}>
        <mesh
            geometry={nodes.Object_4.geometry}
            material={materials['Scene_-_Root']}
            position={[0.438, -0.013, 0.017]}
            rotation={[Math.PI / 2, 0, -Math.PI / 4]}
            scale={[1.376, 1.002, 1]}
        >
          <meshStandardMaterial
            color="#ffeb3b"      // bright yellow
            metalness={0.3}      
            roughness={0.4}      
          /> 
        </mesh>
        </group>
    </Float>
  )
}

useGLTF.preload('/models/javascript.glb')

export default JavascriptLogo
