/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: danielpaulse (https://sketchfab.com/danielpaulse)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/chess-piece-knight-736236d00cfe4cb9a88bee6b4c833e41
Title: Chess Piece - Knight
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const KnightChess = (props) => {
  const { nodes, materials } = useGLTF('/models/chess_piece_-_knight.glb')
  return (
    
    <Float floatIntensity={0.01}>
      <group {...props} dispose={null} scale={22}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.White_Square}
          position={[0.025, 0, 0]}
          scale={1.035}
        />
        {/* <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.Black_Square}
          position={[-0.022, 0, 0]}
          scale={1.035}
        /> */}
      </group>
    </Float>        
  )
}

useGLTF.preload('/models/chess_piece_-_knight.glb')

export default KnightChess