/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: zeeshansattar (https://sketchfab.com/zeeshansattar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-piece-pawn-58ea80dc181241e68096b0559c91a37d
Title: Chess Piece Pawn
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'

const PawnChess = (props) => {
  const { nodes, materials } = useGLTF('/models/chess_piece_pawn.glb')
  return (
    <Float floatIntensity={0.01}> 
      <group {...props} dispose={null} scale={0.15}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Cylinder_0.geometry}
            material={materials['Material.001']}
            position={[0.068, 0, -3.139]}
            scale={[1.966, 1.966, 0.226]}
          />
        </group>
      </group>
    </Float>
  )
}

useGLTF.preload('/models/chess_piece_pawn.glb')

export default PawnChess