/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Amine Hosseini (https://sketchfab.com/suburbandigital)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chess-piece-queen-e1bd054f088e4c928740c4989a4a3a41
Title: Chess Piece Queen
*/

import React, { useRef, useState } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'

const QueenChess = (props) => {
  const { nodes, materials } = useGLTF('/models/chess_piece_queen.glb')

  const queenRef = useRef();
  
  // const [hovered, setHovered] = useState(false);

  // useGSAP(() => {
  //   gsap.timeline({repeat : -1, repeatDelay: 0.5})
  //       .to(queenRef.current.rotation, {
  //         y: hovered ? '+=2' : `+=${Math.PI * 2}`,
  //         x: hovered ? '+=2' : `-=${Math.PI * 2}`,
  //         duration : 2.5,
  //         stagger: {
  //           each: 0.15
  //         },
  //       });
  // });

  return (
    <Float >
      <group {...props} dispose={null} scale={0.18} >
        <mesh
          ref={queenRef}
          geometry={nodes.queen_copy19_lambert4_0.geometry}
          material={materials.lambert4}
          position={[-7.671, 0, 7.592]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={2.54}
          onPointerEnter={() => setHovered(true)}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/models/chess_piece_queen.glb')

export default QueenChess