/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: syeds shoaib (https://sketchfab.com/syeds)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rook-chess-piece-c096a7cfa1934f58b0ef7550057775f8
Title: Rook Chess piece
*/

import React, { useRef } from 'react'
import { Float, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

const RockChess = (props) => {
  const { nodes, materials } = useGLTF('/models/rook_chess_piece.glb');

  const group = useRef();

  // useFrame((state, delta) => {
  //     if (group.current) {
  //         // group.current.rotation.x += delta * 0.01;
  //         // group.current.rotation.x += delta * 0.01;
  //         group.current.rotation.z += delta * 0.1 ;
  //     }
  // });

  return (
    <Float floatIntensity={0.01}>
      <group ref={group} {...props} dispose={null} >
        <mesh
          geometry={nodes.Circle001_Material001_0.geometry}
          material={materials['Material.001']}
          position={[8.76, 9.15, 3.34]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.8}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('/models/rook_chess_piece.glb')

export default RockChess