/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Voldepreuss (https://sketchfab.com/Voldepreuss)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skewed-rubiks-cube-406816c8dc534462a0b71500ddac0f16
Title: Skewed Rubiks Cube
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

const SkewedCube = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/skewed_rubiks_cube.glb')
  const { actions } = useAnimations(animations, group)

  useFrame((state, delta) => {
    if(group.current) {
        group.current.rotation.x += delta * 0.2;
        group.current.rotation.y += delta * 0.4;
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.5}>
          <group name="Root">
            <group name="Empty">
              <group name="321">
                <mesh
                  name="321_0"
                  geometry={nodes['321_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="321_1"
                  geometry={nodes['321_1'].geometry}
                  material={materials.Green}
                />
              </group>
              <group name="311">
                <mesh
                  name="311_0"
                  geometry={nodes['311_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="311_1"
                  
                  geometry={nodes['311_1'].geometry}
                  material={materials.Green}
                />
                <mesh
                  name="311_2"
                  
                  geometry={nodes['311_2'].geometry}
                  material={materials.White}
                />
                <mesh
                  name="311_3"
                  
                  geometry={nodes['311_3'].geometry}
                  material={materials.Orange}
                />
              </group>
              <group name="231">
                <mesh
                  name="231_0"
                  
                  geometry={nodes['231_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="231_1"
                  
                  geometry={nodes['231_1'].geometry}
                  material={materials.material}
                />
                <mesh
                  name="231_2"
                  
                  geometry={nodes['231_2'].geometry}
                  material={materials.Green}
                />
              </group>
              <group name="221">
                <mesh
                  name="221_0"
                  
                  geometry={nodes['221_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="221_1"
                  
                  geometry={nodes['221_1'].geometry}
                  material={materials.Green}
                />
                <mesh
                  name="221_2"
                  
                  geometry={nodes['221_2'].geometry}
                  material={materials.White}
                />
              </group>
              <group name="211">
                <mesh
                  name="211_0"
                  
                  geometry={nodes['211_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="211_1"
                  
                  geometry={nodes['211_1'].geometry}
                  material={materials.White}
                />
              </group>
              <group name="232">
                <mesh
                  name="232_0"
                  
                  geometry={nodes['232_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="232_1"
                  
                  geometry={nodes['232_1'].geometry}
                  material={materials.material}
                />
                <mesh
                  name="232_2"
                  
                  geometry={nodes['232_2'].geometry}
                  material={materials.Yellow}
                />
              </group>
              <group name="222">
                <mesh
                  name="222_0"
                  
                  geometry={nodes['222_0'].geometry}
                  material={materials.Bevel}
                />
              </group>
              <group name="223">
                <mesh
                  name="223_0"
                  
                  geometry={nodes['223_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="223_1"
                  
                  geometry={nodes['223_1'].geometry}
                  material={materials.Yellow}
                />
                <mesh
                  name="223_2"
                  
                  geometry={nodes['223_2'].geometry}
                  material={materials.Blue}
                />
              </group>
              <group name="233">
                <mesh
                  name="233_0"
                  
                  geometry={nodes['233_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="233_1"
                  
                  geometry={nodes['233_1'].geometry}
                  material={materials.Yellow}
                />
              </group>
              <group name="213">
                <mesh
                  name="213_0"
                  
                  geometry={nodes['213_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="213_1"
                  
                  geometry={nodes['213_1'].geometry}
                  material={materials.Blue}
                />
                <mesh
                  name="213_2"
                  
                  geometry={nodes['213_2'].geometry}
                  material={materials.Orange}
                />
              </group>
              <group name="113">
                <mesh
                  name="113_0"
                  
                  geometry={nodes['113_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="113_1"
                  
                  geometry={nodes['113_1'].geometry}
                  material={materials.Blue}
                />
              </group>
              <group name="132">
                <mesh
                  name="132_0"
                  
                  geometry={nodes['132_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="132_1"
                  
                  geometry={nodes['132_1'].geometry}
                  material={materials.material}
                />
              </group>
              <group name="123">
                <mesh
                  name="123_0"
                  
                  geometry={nodes['123_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="123_1"
                  
                  geometry={nodes['123_1'].geometry}
                  material={materials.Blue}
                />
              </group>
              <group name="112">
                <mesh
                  name="112_0"
                  
                  geometry={nodes['112_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="112_1"
                  
                  geometry={nodes['112_1'].geometry}
                  material={materials.White}
                />
                <mesh
                  name="112_2"
                  
                  geometry={nodes['112_2'].geometry}
                  material={materials.Blue}
                />
              </group>
              <group name="111">
                <mesh
                  name="111_0"
                  
                  geometry={nodes['111_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="111_1"
                  
                  geometry={nodes['111_1'].geometry}
                  material={materials.White}
                />
              </group>
              <group name="131">
                <mesh
                  name="131_0"
                  
                  geometry={nodes['131_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="131_1"
                  
                  geometry={nodes['131_1'].geometry}
                  material={materials.material}
                />
              </group>
              <group name="122">
                <mesh
                  name="122_0"
                  
                  geometry={nodes['122_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="122_1"
                  
                  geometry={nodes['122_1'].geometry}
                  material={materials.material}
                />
                <mesh
                  name="122_2"
                  
                  geometry={nodes['122_2'].geometry}
                  material={materials.Blue}
                />
              </group>
              <group name="313">
                <mesh
                  name="313_0"
                  
                  geometry={nodes['313_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="313_1"
                  
                  geometry={nodes['313_1'].geometry}
                  material={materials.Orange}
                />
              </group>
              <group name="323">
                <mesh
                  name="323_0"
                  
                  geometry={nodes['323_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="323_1"
                  
                  geometry={nodes['323_1'].geometry}
                  material={materials.Yellow}
                />
                <mesh
                  name="323_2"
                  
                  geometry={nodes['323_2'].geometry}
                  material={materials.Orange}
                />
              </group>
              <group name="322">
                <mesh
                  name="322_0"
                  
                  geometry={nodes['322_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="322_1"
                  
                  geometry={nodes['322_1'].geometry}
                  material={materials.Green}
                />
                <mesh
                  name="322_2"
                  
                  geometry={nodes['322_2'].geometry}
                  material={materials.Orange}
                />
              </group>
              <group name="133">
                <mesh
                  name="133_0"
                  
                  geometry={nodes['133_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="133_1"
                  
                  geometry={nodes['133_1'].geometry}
                  material={materials.material}
                />
                <mesh
                  name="133_2"
                  
                  geometry={nodes['133_2'].geometry}
                  material={materials.Yellow}
                />
                <mesh
                  name="133_3"
                  
                  geometry={nodes['133_3'].geometry}
                  material={materials.Blue}
                />
              </group>
              <group name="212">
                <mesh
                  name="212_0"
                  
                  geometry={nodes['212_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="212_1"
                  
                  geometry={nodes['212_1'].geometry}
                  material={materials.White}
                />
                <mesh
                  name="212_2"
                  
                  geometry={nodes['212_2'].geometry}
                  material={materials.Orange}
                />
              </group>
              <group name="331">
                <mesh
                  name="331_0"
                  
                  geometry={nodes['331_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="331_1"
                  
                  geometry={nodes['331_1'].geometry}
                  material={materials.Green}
                />
              </group>
              <group name="333">
                <mesh
                  name="333_0"
                  
                  geometry={nodes['333_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="333_1"
                  
                  geometry={nodes['333_1'].geometry}
                  material={materials.Yellow}
                />
              </group>
              <group name="121">
                <mesh
                  name="121_0"
                  
                  geometry={nodes['121_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="121_1"
                  
                  geometry={nodes['121_1'].geometry}
                  material={materials.material}
                />
                <mesh
                  name="121_2"
                  
                  geometry={nodes['121_2'].geometry}
                  material={materials.White}
                />
              </group>
              <group name="312">
                <mesh
                  name="312_0"
                  
                  geometry={nodes['312_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="312_1"
                  
                  geometry={nodes['312_1'].geometry}
                  material={materials.Orange}
                />
              </group>
              <group name="332">
                <mesh
                  name="332_0"
                  
                  geometry={nodes['332_0'].geometry}
                  material={materials.Bevel}
                />
                <mesh
                  name="332_1"
                  
                  geometry={nodes['332_1'].geometry}
                  material={materials.Green}
                />
                <mesh
                  name="332_2"
                  
                  geometry={nodes['332_2'].geometry}
                  material={materials.Yellow}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/skewed_rubiks_cube.glb')

export default SkewedCube